### ISSUE TITLE
Generate genesis-contract

### ISSUE THREAD

**Issue by pablin-dev** [artela-network/artela-rollkit#4]
Problem:

On the `init.sh` bash file there is a call to deploy a [add-genesis-contract](https://github.com/artela-network/artela-rollkit/blob/main/init.sh#L62). 

We would like to use the source file and generate it.
Could you comment how this file is generated?
Thanks!

**Comment by LukeNinjaX** [comment]
Hi @pablin-dev, this section pertains to the account abstraction for specific cases within the Artela Aspect. The source code can be found [here](https://github.com/artela-network/account-abstraction/blob/develop/contracts/core/EntryPoint.sol).
You may disregard it, and if you are not utilizing the Aspect to implement functionalities similar to session keys, feel free to remove the line.

**Comment by pablin-dev** [comment]
Hi @LukeNinjaX. Thank you for your commets! 
You can close the issue.
