### ISSUE TITLE
Generating a new wallet from mnemonics (recover) produces nil pointer exception

### ISSUE THREAD

**Issue by yarikbratashchuk** [artela-network/artela-rollkit#6]
Here is the [issue](https://github.com/Lazychain/artela-rollkit/issues/1) that has to be fixed in the upstream repository.

**Comment by LukeNinjaX** [comment]
Thank you @yarikbratashchuk for debugging the root cause of this issue. The modifications have been uploaded; please refer to https://github.com/artela-network/artela-rollkit/pull/7. If there are any questions, feel free to discuss.
